### ISSUE TITLE
Don't force Screen orientation

### ISSUE THREAD

**Issue by arthurzaczek** [PicFrame/picframe#1]
My Tablett is mounted fix to the wall and shows the settings Screen upside down

**Comment by hclemens** [comment]
If it's in landscape mode, android should handle the orientation as it's supposed to, because we're only forcing landscape, not which "landscape side".
Maybe you're enforcing 270° only on your device (/not allowing 90°)?
Or are you suggesting settings should be available in portrait mode as well?

**Comment by arthurzaczek** [comment]
It's a Android 2.2 issue, Android 2.2 does not know about sensorLandscape

http://stackoverflow.com/questions/12059447/screen-orientation-landscape-upside-down-why

But: The Problem can be worked around with this app:

https://play.google.com/store/apps/details?id=com.googlecode.eyesfree.setorientation&hl=de
