### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by arthurzaczek** [PicFrame/picframe#3]
On my 2.2 Android Tablet I get this Exception:

BRAND=archos
PHONE_MODEL=A101IT
ANDROID_VERSION=2.2.1
APP_VERSION_CODE=4
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:110)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
at java.lang.Thread.run(Thread.java:1096)

**Comment by hclemens** [comment]
We tried to look into that issue today, but couldn't find any specifics. 
It's in  the library after all.
Could you tell us what exactly you tried to do before you got the exception?
Did you edit your owncloud credentials in the app? 
Does the app crash everytime you open it?

**Comment by arthurzaczek** [comment]
It looks like it's in the modified Version of the lib. I didn't added your changes yet.

The only thing I did was setting it up and started the slideshow. Works with the same Owncloud Instance on other Devices (>= 4.2)

**Comment by arthurzaczek** [comment]
This Tablet does not exist anymore
